### ISSUE TITLE
IE11 or Edge support?

### ISSUE THREAD

**Issue by jpolitowski** [JB1905/parlx.js#15]
Is there support for IE11 or Edge? It doesn't seem to work for me, or on the github demo. Thanks!

**Comment by JB1905** [comment]
the library does not support IE11. For Edge, I found an error that caused the incorrect scrolling behavior (getBoundingClientRect (). x is not supported by all browsers). I will release update later today.
Thanks!

**Comment by jpolitowski** [comment]
Amazing. Thank you so much!
